name: ItemizerX
version: 2.1
api-version: 1.17
description: A rewrite of Itemizer
author: Focusvity, Telesphoreo
main: dev.plex.itemizerx.ItemizerX
folia-supported: true
softdepend:
  - CoreProtect
commands:
  itemizer:
    description: The main command for ItemizerX
    usage: /<command>
    aliases: [ii, it]
