name: ItemizerX
version: 3.0
api-version: 1.20
description: A rewrite of Itemizer
author: Focusvity, Telesphoreo
main: dev.plex.itemizerx.ItemizerX
softdepend:
  - CoreProtect
commands:
  itemizer:
    description: The main command for ItemizerX
    usage: /<command>
    aliases: [ii, it]
